name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  geometry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["1.85.0", stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
